import {
  BillingSubscriptionDetails,
  ConnectedRepo,
  Organization,
  PRReviewItem,
  TeamMember,
} from "../../shared/types";

export const MOCK_ORGANIZATIONS: Organization[] = [
  {
    id: "org-1",
    name: "Acme Payments Inc.",
    slug: "acme-payments",
    plan: "TEAM",
    max_seats: 10,
    active_seats_30d: 4,
    subscription_status: "active",
  },
  {
    id: "org-2",
    name: "CloudScale Systems",
    slug: "cloudscale",
    plan: "ENTERPRISE",
    max_seats: 50,
    active_seats_30d: 28,
    subscription_status: "active",
  },
  {
    id: "org-3",
    name: "OpenCore Labs",
    slug: "opencore-labs",
    plan: "FREE",
    max_seats: 1,
    active_seats_30d: 1,
    subscription_status: "active",
  },
];

export const MOCK_MEMBERS: TeamMember[] = [
  {
    id: "mem-1",
    user_id: "usr-1",
    email: "faraz@acmepayments.com",
    username: "farazrasul",
    full_name: "Faraz Rasul",
    role: "OWNER",
    is_active: true,
    created_at: "2026-08-01T10:00:00Z",
  },
  {
    id: "mem-2",
    user_id: "usr-2",
    email: "sarah.dev@acmepayments.com",
    username: "sarahchen",
    full_name: "Sarah Chen",
    role: "ADMIN",
    is_active: true,
    created_at: "2026-08-12T14:30:00Z",
  },
  {
    id: "mem-3",
    user_id: "usr-3",
    email: "marcus.k@acmepayments.com",
    username: "mkaiser",
    full_name: "Marcus Kaiser",
    role: "MEMBER",
    is_active: true,
    created_at: "2026-08-20T09:15:00Z",
  },
  {
    id: "mem-4",
    user_id: "usr-4",
    email: "alex.auditor@acmepayments.com",
    username: "alexa-sec",
    full_name: "Alex Rivera",
    role: "VIEWER",
    is_active: true,
    created_at: "2026-09-01T11:45:00Z",
  },
];

export const MOCK_CONNECTED_REPOS: ConnectedRepo[] = [
  {
    id: "repo-1",
    name: "payment-gateway-service",
    full_name: "acme-payments/payment-gateway-service",
    private: true,
    pr_review_enabled: true,
    secret_scanning_enabled: true,
    quality_gate_enabled: true,
    min_rqi_score: 80,
    active_prs_count: 3,
    last_analyzed_at: "10 minutes ago",
  },
  {
    id: "repo-2",
    name: "auth-ledger-api",
    full_name: "acme-payments/auth-ledger-api",
    private: true,
    pr_review_enabled: true,
    secret_scanning_enabled: true,
    quality_gate_enabled: true,
    min_rqi_score: 75,
    active_prs_count: 1,
    last_analyzed_at: "1 hour ago",
  },
  {
    id: "repo-3",
    name: "customer-checkout-spa",
    full_name: "acme-payments/customer-checkout-spa",
    private: false,
    pr_review_enabled: true,
    secret_scanning_enabled: true,
    quality_gate_enabled: false,
    min_rqi_score: 70,
    active_prs_count: 0,
    last_analyzed_at: "2 days ago",
  },
];

export const MOCK_PR_REVIEWS: PRReviewItem[] = [
  {
    id: "pr-104",
    pr_number: 104,
    pr_title: "feat(crypto): implement AES-256-GCM envelope token encryption",
    repo_full_name: "acme-payments/payment-gateway-service",
    author: "sarahchen",
    head_sha: "e7b8f91a",
    base_sha: "9a2f1c84",
    status: "success",
    rqi_score: 89,
    rqi_delta: 4.2,
    inline_comments_count: 2,
    critical_issues: 0,
    summary:
      "Comprehensive cryptographic upgrade verified. Replaced legacy ECB cipher with AES-256-GCM. 2 inline suggestions generated for nonce uniqueness check.",
    created_at: "2026-09-22T18:42:00Z",
    diff_hunks: [
      {
        file_path: "src/crypto/envelope.ts",
        hunk_header: "@@ -24,8 +24,14 @@ export class EnvelopeEncryptor {",
        lines: [
          { type: "context", content: "  async encrypt(data: Buffer, masterKey: string): Promise<CipherPayload> {" },
          { type: "del", content: "-    const cipher = crypto.createCipher('aes-128-ecb', masterKey);" },
          { type: "add", content: "+    const iv = crypto.randomBytes(12);" },
          { type: "add", content: "+    const cipher = crypto.createCipheriv('aes-256-gcm', keyBuffer, iv);" },
          { type: "context", content: "    const encrypted = Buffer.concat([cipher.update(data), cipher.final()]);" },
          { type: "add", content: "+    const authTag = cipher.getAuthTag();" },
          { type: "add", content: "+    return { encrypted, iv, authTag };" },
          { type: "context", content: "  }" },
        ],
        suggestions: [
          {
            id: "sug-1",
            file_path: "src/crypto/envelope.ts",
            line_start: 26,
            line_end: 27,
            severity: "MEDIUM",
            rule_id: "CRYPTO-GCM-NONCE-CHECK",
            title: "Ensure Nonce Uniqueness under High Throughput",
            explanation:
              "Standard randomBytes(12) is strong, but in ultra-high concurrency distributed services, prepending a sequential counter or host identifier prevents birthday-bound IV reuse.",
            suggested_patch: `    // Ensure 96-bit unique IV combining high-res timestamp and CSPRNG\n    const iv = Buffer.concat([crypto.randomBytes(8), Buffer.alloc(4, Date.now() & 0xffffffff)]);`,
            applied: false,
          },
        ],
      },
    ],
  },
  {
    id: "pr-103",
    pr_number: 103,
    pr_title: "fix(webhook): handle Stripe event retry signature verification",
    repo_full_name: "acme-payments/payment-gateway-service",
    author: "mkaiser",
    head_sha: "3c4a2d10",
    base_sha: "11e9f4b7",
    status: "failure",
    rqi_score: 64,
    rqi_delta: -3.8,
    inline_comments_count: 1,
    critical_issues: 1,
    summary:
      "Quality Gate Failed: High-entropy secret token detected in unit test payload without fixture suppression.",
    created_at: "2026-09-22T14:15:00Z",
    diff_hunks: [
      {
        file_path: "src/webhooks/stripe_handler.ts",
        hunk_header: "@@ -45,6 +45,10 @@ export async function handleStripeWebhook(req: Request) {",
        lines: [
          { type: "context", content: "  const sig = req.headers['stripe-signature'];" },
          { type: "del", content: "-  const secret = process.env.STRIPE_WEBHOOK_SECRET;" },
          { type: "add", content: '+  const secret = process.env.STRIPE_WEBHOOK_SECRET || "whsec_99a8b7c6d5e4f3a2b1";' },
          { type: "context", content: "  return stripe.webhooks.constructEvent(req.body, sig, secret);" },
        ],
        suggestions: [
          {
            id: "sug-2",
            file_path: "src/webhooks/stripe_handler.ts",
            line_start: 47,
            line_end: 47,
            severity: "CRITICAL",
            rule_id: "SECRET-LEAK-HARDCODED-SIGNING-SECRET",
            title: "Hardcoded Webhook Signing Secret Detected",
            explanation:
              "Dual-layer secret scanner detected a live Stripe webhook secret pattern with high Shannon entropy (4.81 bits/sym). Hardcoding fallback signing secrets enables signature forgery.",
            suggested_patch: `  const secret = process.env.STRIPE_WEBHOOK_SECRET;\n  if (!secret) {\n    throw new Error("STRIPE_WEBHOOK_SECRET configuration is missing");\n  }`,
            applied: false,
          },
        ],
      },
    ],
  },
];

export const MOCK_BILLING_DETAILS: BillingSubscriptionDetails = {
  organization_id: "org-1",
  plan: "TEAM",
  subscription_status: "active",
  max_seats: 10,
  active_seats_30d: 4,
  monthly_scans_used: 142,
  max_monthly_scans: 1000,
  entitlements: {
    allow_private_repos: true,
    allow_inline_suggestions: true,
    allow_secret_scanning: true,
    allow_custom_rules: true,
    priority_queue: true,
  },
  active_authors: [
    { github_author: "farazrasul", last_pr_at: "2026-09-22T20:10:00Z" },
    { github_author: "sarahchen", last_pr_at: "2026-09-22T18:42:00Z" },
    { github_author: "mkaiser", last_pr_at: "2026-09-22T14:15:00Z" },
    { github_author: "dev-bot-lead", last_pr_at: "2026-09-18T11:05:00Z" },
  ],
};
