"""initial_commercial_schema

Revision ID: a3da0c68e54a
Revises: 
Create Date: 2026-09-23 00:51:31.358994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3da0c68e54a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('plan', sa.Enum('FREE', 'TEAM', 'ENTERPRISE', name='orgplan', native_enum=False), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_status', sa.String(length=50), nullable=False),
    sa.Column('max_monthly_scans', sa.Integer(), nullable=False),
    sa.Column('monthly_scans_used', sa.Integer(), nullable=False),
    sa.Column('max_seats', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('github_installation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_github_installation_id'), 'organizations', ['github_installation_id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_index(op.f('ix_organizations_stripe_customer_id'), 'organizations', ['stripe_customer_id'], unique=False)
    op.create_table('processed_webhook_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_webhook_events_event_id'), 'processed_webhook_events', ['event_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('github_id', sa.Integer(), nullable=True),
    sa.Column('github_username', sa.String(length=100), nullable=True),
    sa.Column('encrypted_github_token', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_index(op.f('ix_users_github_username'), 'users', ['github_username'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('active_authors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('author_email', sa.String(length=255), nullable=False),
    sa.Column('author_name', sa.String(length=200), nullable=True),
    sa.Column('last_commit_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'author_email', name='uq_org_author_email')
    )
    op.create_index(op.f('ix_active_authors_author_email'), 'active_authors', ['author_email'], unique=False)
    op.create_index(op.f('ix_active_authors_last_commit_at'), 'active_authors', ['last_commit_at'], unique=False)
    op.create_index(op.f('ix_active_authors_organization_id'), 'active_authors', ['organization_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_prefix', sa.String(length=30), nullable=False),
    sa.Column('hashed_key', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_hashed_key'), 'api_keys', ['hashed_key'], unique=True)
    op.create_index(op.f('ix_api_keys_organization_id'), 'api_keys', ['organization_id'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='userrole', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_user_organization')
    )
    op.create_index(op.f('ix_memberships_organization_id'), 'memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('repositories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_branch', sa.String(length=100), nullable=False),
    sa.Column('primary_language', sa.String(length=50), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('disk_size_bytes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_name'), 'repositories', ['name'], unique=False)
    op.create_index(op.f('ix_repositories_organization_id'), 'repositories', ['organization_id'], unique=False)
    op.create_index(op.f('ix_repositories_url'), 'repositories', ['url'], unique=True)
    op.create_table('analysis_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'CLONING', 'INDEXING', 'STATIC_ANALYSIS', 'DEFECT_PREDICTION', 'AI_REVIEW', 'AGGREGATING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_repository_id'), 'analysis_jobs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_status'), 'analysis_jobs', ['status'], unique=False)
    op.create_table('analysis_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('maintainability_score', sa.Float(), nullable=False),
    sa.Column('security_score', sa.Float(), nullable=False),
    sa.Column('testing_score', sa.Float(), nullable=False),
    sa.Column('architecture_score', sa.Float(), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('total_lines_of_code', sa.Integer(), nullable=False),
    sa.Column('total_functions', sa.Integer(), nullable=False),
    sa.Column('total_classes', sa.Integer(), nullable=False),
    sa.Column('technical_debt_minutes', sa.Integer(), nullable=False),
    sa.Column('summary_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_reports_job_id'), 'analysis_reports', ['job_id'], unique=True)
    op.create_table('defect_predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('defect_probability', sa.Float(), nullable=False),
    sa.Column('risk_tier', sa.Enum('CRITICAL', 'HIGH', 'MODERATE', 'LOW', name='risktier'), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('shap_factors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['analysis_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defect_predictions_file_path'), 'defect_predictions', ['file_path'], unique=False)
    op.create_index(op.f('ix_defect_predictions_report_id'), 'defect_predictions', ['report_id'], unique=False)
    op.create_index(op.f('ix_defect_predictions_risk_tier'), 'defect_predictions', ['risk_tier'], unique=False)
    op.create_table('file_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('sloc', sa.Integer(), nullable=False),
    sa.Column('cyclomatic_complexity', sa.Integer(), nullable=False),
    sa.Column('cognitive_complexity', sa.Integer(), nullable=False),
    sa.Column('function_count', sa.Integer(), nullable=False),
    sa.Column('class_count', sa.Integer(), nullable=False),
    sa.Column('maintainability_index', sa.Float(), nullable=False),
    sa.Column('halstead_metrics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['analysis_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_metrics_file_path'), 'file_metrics', ['file_path'], unique=False)
    op.create_index(op.f('ix_file_metrics_report_id'), 'file_metrics', ['report_id'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('SECURITY', 'CODE_SMELL', 'BUG_RISK', 'PERFORMANCE', 'MAINTAINABILITY', 'ARCHITECTURE', name='findingcategory'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='findingseverity'), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('cwe_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['analysis_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_category'), 'issues', ['category'], unique=False)
    op.create_index(op.f('ix_issues_file_path'), 'issues', ['file_path'], unique=False)
    op.create_index(op.f('ix_issues_report_id'), 'issues', ['report_id'], unique=False)
    op.create_index(op.f('ix_issues_rule_id'), 'issues', ['rule_id'], unique=False)
    op.create_index(op.f('ix_issues_severity'), 'issues', ['severity'], unique=False)
    op.create_table('review_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('suggested_patch', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DISMISSED', name='commentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['analysis_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_comments_file_path'), 'review_comments', ['file_path'], unique=False)
    op.create_index(op.f('ix_review_comments_report_id'), 'review_comments', ['report_id'], unique=False)
    op.create_index(op.f('ix_review_comments_status'), 'review_comments', ['status'], unique=False)

    # PostgreSQL Row-Level Security (RLS) activation for multi-tenant isolation
    bind = op.get_bind()
    if bind and bind.dialect.name == "postgresql":
        tenant_tables = [
            "repositories", "analysis_jobs", "analysis_reports",
            "defect_predictions", "file_metrics", "issues",
            "review_comments", "api_keys", "audit_logs", "active_authors"
        ]
        for tbl in tenant_tables:
            op.execute(f"ALTER TABLE {tbl} ENABLE ROW LEVEL SECURITY;")
            op.execute(
                f"CREATE POLICY {tbl}_tenant_isolation_policy ON {tbl} "
                f"FOR ALL USING (organization_id = NULLIF(current_setting('app.current_org_id', true), ''));"
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_comments_status'), table_name='review_comments')
    op.drop_index(op.f('ix_review_comments_report_id'), table_name='review_comments')
    op.drop_index(op.f('ix_review_comments_file_path'), table_name='review_comments')
    op.drop_table('review_comments')
    op.drop_index(op.f('ix_issues_severity'), table_name='issues')
    op.drop_index(op.f('ix_issues_rule_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_report_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_file_path'), table_name='issues')
    op.drop_index(op.f('ix_issues_category'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_file_metrics_report_id'), table_name='file_metrics')
    op.drop_index(op.f('ix_file_metrics_file_path'), table_name='file_metrics')
    op.drop_table('file_metrics')
    op.drop_index(op.f('ix_defect_predictions_risk_tier'), table_name='defect_predictions')
    op.drop_index(op.f('ix_defect_predictions_report_id'), table_name='defect_predictions')
    op.drop_index(op.f('ix_defect_predictions_file_path'), table_name='defect_predictions')
    op.drop_table('defect_predictions')
    op.drop_index(op.f('ix_analysis_reports_job_id'), table_name='analysis_reports')
    op.drop_table('analysis_reports')
    op.drop_index(op.f('ix_analysis_jobs_status'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_repository_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index(op.f('ix_repositories_url'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_organization_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_name'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_organization_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_organization_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_hashed_key'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_active_authors_organization_id'), table_name='active_authors')
    op.drop_index(op.f('ix_active_authors_last_commit_at'), table_name='active_authors')
    op.drop_index(op.f('ix_active_authors_author_email'), table_name='active_authors')
    op.drop_table('active_authors')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_github_username'), table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_processed_webhook_events_event_id'), table_name='processed_webhook_events')
    op.drop_table('processed_webhook_events')
    op.drop_index(op.f('ix_organizations_stripe_customer_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_github_installation_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
